### ISSUE TITLE
Improve topic/feature visibility 

### ISSUE THREAD

**Issue by mikemhenry** [glotzerlab/signac-docs#76]
We have this: https://docs.signac.io/en/latest/reference.html

But maybe need a way to organize the order/what topics people should check out.

**Comment by vyasr** [comment]
@atravitz @klywang this is probably relevant to our discussion today

**Comment by cbkerr** [comment]
#97 improves the visibility of topics, so if this PR is still relevant, maybe we can change the focus to be the ordering that @mikemhenry mentioned:
>But maybe need a way to organize the order/what topics people should check out.

**Comment by kidrahahjo** [comment]
@vyasr is this issue still relevant (or requires attention)? I see some work has been done like @cbkerr mentioned

**Comment by vyasr** [comment]
I think that's a question for @cbkerr and @atravitz. There was further work done to improve the docs even since the last comment here, @atravitz should we consider this issue resolved for now? The problem with any issue like "Improve..." is that it's inherently a bit nebulous in scope. We should either use this issue as a catch-all and include lots of detailed notes/checklist/to-do items, or clearly delineate how far this issue should go and open future (more tightly scoped) issues to address specific considerations for improvement.

**Comment by cbkerr** [comment]
@vyasr I agree that issues like this should be specific enough to know when they're done. #85 by @klywang is a great example of this :)

I'm going to go ahead and close this because in the course of all the docs work we did over the summer, we've even [removed the "references" page linked in the original comment](https://github.com/glotzerlab/signac-docs/pull/97/commits/55f08b1eb5c27669b7aec55797ee274439ed18ad), which to me is as done as it gets!
