### ISSUE TITLE
Expand Navigation bar to expose more content

### ISSUE THREAD

**Issue by klywang** [glotzerlab/signac-docs#85]
### Issue Description

The current Navigation bar layout has too many levels. It is difficult to find articles related to specific topics a user may be interested in

For example, if a user wishes wants to look up state point modification, they must navigate to `User Guide (section) > Managing Data (level 1) > Jobs (level 2) > The Job State Point (level 3) >  Modifying the State Point (heading in The Job State Point)`.

### Proposed change

Reduce the number of levels a user must navigate through to find specific topics. An example of the proposed navigation bar is provided below

![image](https://user-images.githubusercontent.com/47036428/79783794-34b13c00-830f-11ea-8752-ffec5f693ee4.png)
Where *User Guide* is replaced with *Topic Guide*, *Packages (API)*, and *Recipes (How to)*

**Comment by vyasr** [comment]
Is there any way in Sphinx to require that a sidebar show multiple levels by default, rather than having to click into a level before you can see that output? And if that exists, @klywang would that also resolve the problem, or would you still prefer to just see a flattened structure?

**Comment by klywang** [comment]
@vyasr That might make give users information overload and make things harder to find. I think the flattened structure is good, it just needs to be more obvious where to find the information you need.

**Comment by csadorf** [comment]
> Is there any way in Sphinx to require that a sidebar show multiple levels by default, rather than having to click into a level before you can see that output? And if that exists, @klywang would that also resolve the problem, or would you still prefer to just see a flattened structure?

Yes, see the `maxdepth` option for the `toctree` directive: https://www.sphinx-doc.org/en/1.5/markup/toctree.html#directive-toctree

**Comment by cbkerr** [comment]
> Is there any way in Sphinx to require that a sidebar show multiple levels by default, rather than having to click into a level before you can see that output?
I found an option to fix this problem in #93.

**Comment by cbkerr** [comment]
I agree with @klywang that there are too many navigation levels in the current documentation. In the commits towards #93, I experimented with setting read-the-docs theme property`navigation_depth` to 3 (one less than default, [described here](https://sphinx-rtd-theme.readthedocs.io/en/stable/configuring.html)), but since the sub-sections are long, the subheadings feel necessary until some content can be rearranged.

Note that when I use the documentation, I often barely notice the blue text (like "Getting Started") because it stands out less than the white text.

I support @klywang's amended top-level headings "Getting Started", "Topic Guides", "Packages (API)", and "How-To" as well as her reshuffled TOC.

**Comment by atravitz** [comment]
#95 can be addressed in this PR too I think.

**Comment by cbkerr** [comment]
I just noticed that many sections aren't discoverable by moving elements of the "reference.rst" file to the sidebar. These are: operations, flow-project, cluster_submission, environments, templates, flow-group, indexing, collections, configuration.

The original re-organization proposed by @klywang has some of these (collections, configuration), but not all. I think "workflows" contains sub-pages. Adding these to the sidebar under "Topic Guides" would make for a long sidebar, but maybe that's not a terribly bad thing.
